### ISSUE TITLE
login failed for password_error

### ISSUE THREAD

**Issue by NoelzeN** [emqx/emqx-auth-mysql#100]
When trying to authenticate, I get an error message saying
(emq@127.0.0.1)1> 11:20:14.090 [error] Client(iot_monitoring@80.241.214.158:36988): Username 'iot_monitoring' login failed for password_error

I have just enabled the MySQL Plugin and added the User to it manually trying to follow the description in the readme file of the plugin.

Interesting Config Parts of the MySQL Plugin:
>auth.mysql.auth_query = select password from mqtt_user where username = '%u' limit 1
auth.mysql.password_hash = plain
auth.mysql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'

Database Content:
>+----+----------------+---------------------------------------------------------+------+--------------+---------------------+
| id | username       | password                                                | salt | is_superuser | created             |
+----+----------------+---------------------------------------------------------+------+--------------+---------------------+
|  1 | iot_monitoring | [PASSWORD] |      |            0 | 2018-11-06 10:50:55 |
+----+----------------+---------------------------------------------------------+------+--------------+---------------------+
1 row in set (0.00 sec)

On the Client Side I get

>Error: Connection refused: Bad username or password

List of active Plugins:

>Plugin(emq_auth_clientid, version=2.3.9, description=Authentication with ClientId/Password, active=false)
Plugin(emq_auth_http, version=2.3.9, description=Authentication/ACL with HTTP API, active=false)
Plugin(emq_auth_jwt, version=2.3.9, description=Authentication with JWT, active=false)
Plugin(emq_auth_ldap, version=2.3.9, description=Authentication/ACL with LDAP, active=false)
Plugin(emq_auth_mongo, version=2.3.9, description=Authentication/ACL with MongoDB, active=false)
Plugin(emq_auth_mysql, version=2.3.9, description=Authentication/ACL with MySQL, active=true)
Plugin(emq_auth_pgsql, version=2.3.9, description=Authentication/ACL with PostgreSQL, active=false)
Plugin(emq_auth_redis, version=2.3.9, description=Authentication/ACL with Redis, active=false)
Plugin(emq_auth_username, version=2.3.9, description=Authentication with Username/Password, active=true)
Plugin(emq_coap, version=2.3.9, description=CoAP Gateway, active=false)
Plugin(emq_dashboard, version=2.3.9, description=EMQ Web Dashboard, active=true)
Plugin(emq_lua_hook, version=2.3.9, description=EMQ Hooks in lua, active=false)
Plugin(emq_modules, version=2.3.9, description=EMQ Modules, active=true)
Plugin(emq_plugin_template, version=2.3.9, description=EMQ Plugin Template, active=false)
Plugin(emq_recon, version=2.3.9, description=Recon Plugin, active=true)
Plugin(emq_reloader, version=2.3.9, description=Reloader Plugin, active=false)
Plugin(emq_retainer, version=2.3.9, description=EMQ Retainer, active=true)
Plugin(emq_sn, version=2.3.9, description=MQTT-SN Gateway, active=false)
Plugin(emq_stomp, version=2.3.9, description=Stomp Protocol Plugin, active=false)
Plugin(emq_web_hook, version=2.3.9, description=EMQ Webhook Plugin, active=false)

The username is not used in the emq_auth_username file so there is no password mismatch there. Is there a way to debug this better? Thanks a lot, Nils

**Comment by lidraikh** [comment]
Hi , i'm having a similar problem.
 we trying to use Mysql plugin to manage users,  but I'm getting the same error, each time MQTT client try to connect I get this in the error log
'2019-01-08 19:51:54.422 [error] 12321342342341546995078799@107.142.20.244:63533 [MQTT] Username 'rootuser' login failed for password_error'

I don't have any other authentication plugin enabled.

'''
Plugin(emqx_auth_clientid, version=3.0, description=EMQ X Authentication with ClientId/Password, active=false)
Plugin(emqx_auth_http, version=3.0, description=EMQ X Authentication/ACL with HTTP API, active=false)
Plugin(emqx_auth_jwt, version=3.0, description=EMQ X Authentication with JWT, active=false)
Plugin(emqx_auth_ldap, version=3.0, description=EMQ X Authentication/ACL with LDAP, active=false)
Plugin(emqx_auth_mongo, version=3.0, description=EMQ X Authentication/ACL with MongoDB, active=false)
Plugin(emqx_auth_mysql, version=3.0, description=EMQ X Authentication/ACL with MySQL, active=true)
Plugin(emqx_auth_pgsql, version=3.0, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
Plugin(emqx_auth_redis, version=3.0, description=EMQ X Authentication/ACL with Redis, active=false)
Plugin(emqx_auth_username, version=3.0, description=EMQ X Authentication with Username and Password, active=false)
Plugin(emqx_coap, version=3.0, description=EMQ X CoAP Gateway, active=false)
Plugin(emqx_dashboard, version=3.0, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_delayed_publish, version=3.0, description=EMQ X Delayed Publish, active=false)
Plugin(emqx_lua_hook, version=3.0, description=EMQ X Lua Hooks, active=false)
Plugin(emqx_lwm2m, version=3.0, description=EMQ X LwM2M Gateway, active=false)
Plugin(emqx_management, version=3.0, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_plugin_template, version=3.0, description=EMQ X Plugin Template, active=false)
Plugin(emqx_recon, version=3.0, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_reloader, version=3.0, description=EMQ X Reloader Plugin, active=false)
Plugin(emqx_retainer, version=3.0, description=EMQ X Retainer, active=true)
Plugin(emqx_sn, version=3.0, description=EMQ X MQTT SN Plugin, active=false)
Plugin(emqx_statsd, version=3.0, description=Statsd for EMQ X, active=false)
Plugin(emqx_stomp, version=3.0, description=EMQ X Stomp Protocol Plugin, active=false)
Plugin(emqx_web_hook, version=3.0, description=EMQ X Webhook Plugin, active=false)
'''

your help is appreciated

**Comment by lidraikh** [comment]
Ok Allow me to apologize, it turned out this is my mistake.
I used the mqtt.sql file to create the database and did not set any password hashing, but plugin configuration had **sh256** set as hashing.

defoult configration 
```
## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
auth.mysql.password_hash = sha256
```

the new configuration is 
```
## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
auth.mysql.password_hash = **plain**
```

it may guide someone later.
Thanks again
