### ISSUE TITLE
Mysql认证的SuperUser怎么用

### ISSUE THREAD

**Issue by wwhai** [emqx/emqx-auth-mysql#159]
请问一下SuperUser主要用途是什么，在文档里面没看到

**Comment by HJianBo** [comment]
Hi, @wwhai The super user have all of the topics access right.

That means the super user can subscribe any topics and publish a message to any topic

**Comment by wwhai** [comment]
> Hi, @wwhai The super user have all of the topics access right.
> 
> That means the super user can subscribe any topics and publish a message to any topic

Thank you！
