### ISSUE TITLE
Location folder file .conf

### ISSUE THREAD

**Issue by renerlemes** [emqx/emqx-auth-mysql#183]
Where is the configuration file located. Because I change the dashboard and when I restart the service it returns the default settings

**Comment by tigercl** [comment]
Hi, @renerlemes. The configuration file is `.../emqx/etc/plugins/emqx_auth_mysql.conf`.

**Comment by renerlemes** [comment]
I did not find this path. But I found `.../etc/emqx/plugins/emqx_auth_mysql.conf`. Is correct?

**Comment by tigercl** [comment]
@renerlemes. That's right.
