### ISSUE TITLE
MySQL 8

### ISSUE THREAD

**Issue by vangalvin** [emqx/emqx-auth-mysql#184]
I have just EMQ on a Ubuntu system that is running MySQL Version 8 and when trying to load the plugin I am getting the following error.

`load plugin error: {emqx_auth_mysql,
                    {bad_return,
                     {{emqx_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emqx_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {1045,<<"28000">>,
                                 <<"Access denied for user 'mqtt'@'localhost' (using password: YES)">>}}}}}}}}},
                        [{emqx_auth_mysql_app,start,2,
                          [{file,
                            "/emqx_temp/emqx_rel/_checkouts/emqx_auth_mysql/src/emqx_auth_mysql_app.erl"},
                           {line,36}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}}
`
Any suggestions as to what is causing this?

**Comment by HJianBo** [comment]
> <<"Access denied for user 'mqtt'@'localhost' (using password: YES)">>}

It seems that the username configured in `emqx_auth_mysql.conf` can not log in MySQL.
Please make sure it is correct

**Comment by ChinaChenjinlin** [comment]
我也遇到这种情况了,emqx版本3.2.7; mysql版本8.0.16; 加载emqx_auth_mysql时就出错

**Comment by HJianBo** [comment]
This doc maybe helo you https://docs.emqx.io/broker/latest/en/faq/error.html#emq-x-cannot-connect-to-mysql80
