### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by renerlemes** [emqx/emqx-auth-mysql#190]
I have a custom table using the follow query:

`SELECT '25d55ad283aa400af464c76d713c07ad' AS password FROM UsuarioDispositivo ud INNER JOIN Dispositivo d ON d.Id = ud.IdDispositivo WHERE d.MacAddress = '%u' AND d.MacAddress = '%c' LIMIT 1`

When I try to connect, the device is connected to mqtt but could not connect because the query result is 0

**Comment by renerlemes** [comment]
The problemn is that allow_anonymous = true in emqx.conf is true, but when I set to false, the erro occurs:

2019-12-13T08:11:19.447000-03:00 [error] Syntax error in c:/emqx/data/configs/app.2019.12.13.08.11.18.conf after line 1 column 1, parsing incomplete

**Comment by tigercl** [comment]
@renerlemes When you modify `emqx.conf`, you introduce some special characters that cause it parsing to fail. It is recommended to modify `emqx.conf` directly through `vim`.

**Comment by renerlemes** [comment]
@tigercl tks.
