### ISSUE TITLE
Load emqx-auth-mysql failed

### ISSUE THREAD

**Issue by tangliming** [emqx/emqx-auth-mysql#199]
Hi,

I am using the windows version of emqx 4.0.0 and create the corresponding mysql database and tables for user authentication and acl. But when I load the plugin, it gives me the below error:

`D:\tmp\emqx\bin>emqx_ctl plugins load emqx_auth_mysql
Load plugin emqx_auth_mysql error: {emqx_auth_mysql,
                                    {bad_return,
                                     {{emqx_auth_mysql_app,start,[normal,[]]},
                                      {'EXIT',
                                       {{badmatch,
                                         {error,
                                          {shutdown,
                                           {failed_to_start_child,
                                            emqx_auth_mysql,
                                            {shutdown,
                                             {failed_to_start_child,
                                              worker_sup,
                                              {shutdown,
                                               {failed_to_start_child,
                                                {worker,1},
                                                {{auth_method,
                                                  <<"caching_sha2_password">>},
                                                 [{mysql_protocol,
                                                   build_handshake_response,5,
                                                   [{file,
                                                     "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"},
                                                    {line,386}]},
                                                  {mysql_protocol,handshake,
                                                   7,
                                                   [{file,
                                                     "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"},
                                                    {line,72}]},
                                                  {mysql_conn,init,1,
                                                   [{file,
                                                     "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/mysql/src/mysql_conn.erl"},
                                                    {line,108}]},
                                                  {gen_server,init_it,2,
                                                   [{file,"gen_server.erl"},
                                                    {line,374}]},
                                                  {gen_server,init_it,6,
                                                   [{file,"gen_server.erl"},
                                                    {line,342}]},
                                                  {proc_lib,init_p_do_apply,
                                                   3,
                                                   [{file,"proc_lib.erl"},
                                                    {line,249}]}]}}}}}}}}},
                                        [{emqx_auth_mysql_app,start,2,
                                          [{file,
                                            "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx_auth_mysql/src/emqx_auth_mysql_app.erl"},
                                           {line,38}]},
                                         {application_master,start_it_old,4,
                                          [{file,"application_master.erl"},
                                           {line,277}]}]}}}}}.`
could u please tell me how can I solve this? Thanks a lot.

**Comment by HJianBo** [comment]
Hi, @tangliming Pls see [FAQ - emq-x-cannot-connect-to-mysql8](https://docs.emqx.io/faq/latest/en/errors.html#emq-x-cannot-connect-to-mysql80)

Hope it works for you

**Comment by tangliming** [comment]
> Hi, @tangliming Pls see [FAQ - emq-x-cannot-connect-to-mysql8](https://docs.emqx.io/faq/latest/en/errors.html#emq-x-cannot-connect-to-mysql80)
> 
> Hope it works for you

Thanks HJianBo, downgrade mysql to 5.7.X fix this issue.
