### ISSUE TITLE
I having struggle writing a query

### ISSUE THREAD

**Issue by bkrajendra** [emqx/emqx-auth-mysql#201]
For auth query:
```
auth.mysql.auth_query = select password_hash as password from mqtt_user where username = '%u' limit 1
```
for my table with **email as username** and  table name **users** i have written:

```
auth.mysql.auth_query = select password, email as username  from users having username = '%u' limit 1
```

I have different field name for username column and you cant write alias in where clause. hence im using HAVING.
But still my above query not working.

Please help.

**Comment by zhengyupan** [comment]
Hi @bkrajendra ,
the auth query requires only one column, your query returns two. And the 'having' clause could be unnecessary, single 'where' without 'having' should do the job already.
Please try: select password from users where email = '%u' limit 1
Please modify above query if need.

**Comment by bkrajendra** [comment]
Hi @zhengyupan , yes i realized it latter and changed my query to:

```
select password from (SELECT password, email AS username FROM users) as mqtt_user WHERE username = '%u' limit 1
```

and it started working.

**Comment by zhengyupan** [comment]
@bkrajendra nice to hear that.
Is it ok to close this issue?
