### ISSUE TITLE
mysql8 错误

### ISSUE THREAD

**Issue by ChinaChenjinlin** [emqx/emqx-auth-mysql#205]
Load plugin emqx_auth_mysql error: {emqx_auth_mysql,
                                    {bad_return,
                                     {{emqx_auth_mysql_app,start,[normal,[]]},
                                      {'EXIT',
                                       {{badmatch,
                                         {error,
                                          {shutdown,
                                           {failed_to_start_child,
                                            emqx_auth_mysql,
                                            {shutdown,
                                             {failed_to_start_child,
                                              worker_sup,
                                              {shutdown,
                                               {failed_to_start_child,
                                                {worker,1},
                                                {{auth_method,
                                                  <<"caching_sha2_password">>},
                                                 [{mysql_protocol,
                                                   build_handshake_response,5,
                                                   [{file,
                                                     "/emqx-rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"},
                                                    {line,386}]},
                                                  {mysql_protocol,handshake,
                                                   7,
                                                   [{file,
                                                     "/emqx-rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"},
                                                    {line,72}]},
                                                  {mysql_conn,init,1,
                                                   [{file,
                                                     "/emqx-rel/_build/emqx/lib/mysql/src/mysql_conn.erl"},
                                                    {line,108}]},
                                                  {gen_server,init_it,2,
                                                   [{file,"gen_server.erl"},
                                                    {line,374}]},
                                                  {gen_server,init_it,6,
                                                   [{file,"gen_server.erl"},
                                                    {line,342}]},
                                                  {proc_lib,init_p_do_apply,
                                                   3,
                                                   [{file,"proc_lib.erl"},
                                                    {line,249}]}]}}}}}}}}},
                                        [{emqx_auth_mysql_app,start,2,
                                          [{file,
                                            "/emqx-rel/_build/emqx/lib/emqx_auth_mysql/src/emqx_auth_mysql_app.erl"},
                                           {line,38}]},
                                         {application_master,start_it_old,4,
                                          [{file,"application_master.erl"},
                                           {line,277}]}]}}}}}.

emqx版本为3.1.1 和 3.2.7 和4.0.0我都试过了;都无法加载emqx_auth_mysql插件; 都可以加载mysql5.7版本的; mysql8的都不行;

**Comment by HJianBo** [comment]
Plz see: https://docs.emqx.io/faq/latest/cn/errors.html#emq-x-无法连接-mysql-80
