### ISSUE TITLE
 Failed to execute {fun emqx_acl_mysql:check_acl/5

### ISSUE THREAD

**Issue by Myuhua** [emqx/emqx-auth-mysql#254]
Failed to execute {fun emqx_acl_mysql:check_acl/5

**Comment by Myuhua** [comment]
[Hooks] Failed to execute {fun emqx_acl_mysql:check_acl/5,
                           [#{acl_query =>
                                  {"select allow, ipaddr, username, clientid, access, topic from mqtt_acl where username = ?",

**Comment by Myuhua** [comment]
[Hooks] Failed to execute {fun emqx_acl_mysql:check_acl/5,
[#{acl_query =>
{"select allow, ipaddr, username, clientid, access, topic from mqtt_acl where username = ?",


Is this a bug or am i having a configuration error?
I also checked the other issues on that, but their solutions didnt work for me...

Thanks a lot!

**Comment by HJianBo** [comment]
@Myuhua Could you send me the complete error logs and emqx_auth_mysql.conf ?

**Comment by Myuhua** [comment]
> Could you paste the complete error logs and emqx_auth_mysql.conf here
@HJianBo My problem has been solved. Thanks for your comment.

**Comment by nnilsson123** [comment]
> 
> 
> > Could you paste the complete error logs and emqx_auth_mysql.conf here
> > @HJianBo My problem has been solved. Thanks for your comment.

How was this solved?
