### ISSUE TITLE
pbkdf2 doesn't work 

### ISSUE THREAD

**Issue by aruldd** [emqx/emqx-auth-mysql#85]
PBKDF2 doesn't work even with the test data, throws pbkdf2  

> login failed for password_error

Details of the environment

- ubuntu 16.04.
- installed with deb from emqtt.io
- created the tables with the create script from the documentation.
- data from the insert queries in tests.
- configured the plugin using the web dashboard.

**Comment by SimonFuu** [comment]
meet the same issue emqtt 2.3.10(macOS 10.13 version) running on macOS 10.13.6.
I have passed the testings by plain/sha256/salt,sha256 but failed on pbkd2.

**Comment by ngjaying** [comment]
@aruldd @SimonFuu It works fine for me on emqx 3.0. If you still have the issue, could you provide the following info:

1. Your emqx_auth_mysql.conf for auth.mysql.password_hash and auth.mysql.auth_query
2. The user data in mysql for a particular user , get it by 
```sql
select * from `mqtt_user` where `username`= <yourusernamehere>
```
3. The plain text password for that user

We can do more investigation based on the further information.
