### ISSUE TITLE
Error on mysql server

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx-auth-mysql#99]
I got this error on my mysql 5.7 docker container when using EMQX 3.0 beta 4:
[Note] Aborted connection 53 to db: 'xxx' user: 'xxx' host: 'xx.xx.xx.xx' (Got an error reading communication packets)

I havent got this issue when using it on EMQ 2.3.11.

**Comment by Gilbert-Wong** [comment]
Thanks for your issue, we'll check it and make sure it has been fixed in emqx rc 2.
